### ISSUE TITLE
To Do list is undefined

### ISSUE THREAD

**Issue by johndavidsimmons** [AdobeDocs/adobeio-samples-todolist#1]
I have tried working through the lab and running this repo verbatim and I can't get the empty todo list to load for the first time. Everything compiles and loads fine, but the todoList is always undefined. I have added my name and authspace to an .env file.

In the action:
```
    let todoList = (await state.get(`todolist`)) || [];
    if (todoList) {
      todoList = todoList.value;
    }
```

In app.js, (console logs added by me)
```  // Show the loading indicator while fetching the todo lists
  useEffect(() => {
    (async () => {
      const { todoList } = await action('read');
      console.log('*************');
      console.log(todoList);
      console.log('*************');
      if (todoList) {
        setTodoList(todoList);
        setIsLoading(false);
      }
    })();
  }, []);
```

![Screen Shot 2021-06-22 at 5 18 42 PM](https://user-images.githubusercontent.com/8012764/123001064-53c9b480-d37e-11eb-8376-95414eba9598.png)

**Comment by icaraps** [comment]
@johndavidsimmons Thanks for reporting ! I fixed it in f9fde47.
